export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const LOGIN_USER = "LOGIN_USER";
export const SIGNUP_USER = "SIGN_UP_USER";
export const FETCH_DEPARTMENTS = "FETCH_DEPARTMENTS";
export const FETCH_PRODUCTS_BY_DEPARTMENT = "FETCH_PRODUCTS_BY_DEPARTMENT";
export const FETCH_PRODUCTS_BY_CATEGORY = "FETCH_PRODUCTS_BY_CATEGORY";
export const FETCH_CATEGORIES_PER_DEPARTMENT =
  "FETCH_CATEGORIES_PER_DEPARTMENT";
export const FETCH_CART_ITEMS = "FETCH_CART_ITEMS";
export const FETCH_TOTAL_AMOUNT = "FETCH_TOTAL_AMOUNT";
export const GENERATE_CART_ID = "GENERATE_CART_ID";
export const HIDE_MODAL = "HIDE_MODAL";
export const SHOW_MODAL = "SHOW_MODAL";
export const EMPTY_SHOPPING_CART = "EMPTY_SHOPPING_CART";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCT_REVIEWS = "FETCH_PRODUCT_REVIEWS";
export const FETCH_PRODUCT_ATTRIBUTES = "FETCH_PRODUCT_ATTRIBUTES";
