export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const LOGIN_USER = "LOGIN_USER";
export const SIGNUP_USER = "SIGN_UP_USER";
export const FETCH_DEPARTMENTS = "FETCH_DEPARTMENTS";
export const FETCH_PRODUCTS_BY_DEPARTMENT = "FETCH_PRODUCTS_BY_DEPARTMENT";
export const FETCH_PRODUCTS_BY_CATEGORY = "FETCH_PRODUCTS_BY_CATEGORY";
export const FETCH_CATEGORIES_PER_DEPARTMENT = "FETCH_CATEGORIES_PER_DEPARTMENT";